name: Additional UI Components NPM

on:
  workflow_call:
    inputs:
      release-version:
        description: The release version number (e.g. 1.2.4)
        type: string
        required: true
  workflow_dispatch:
    inputs:
      release-version:
        description: The release version number (e.g. 1.2.4)
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check release version in package.json
        run: |
          if ! grep -q "  \"version\": \"${VERSION}\"" libs/custom-ui-components/package.json; then
            echo "Error: Release version ${{ inputs.release-version }} not found in package.json"
            exit 1
          fi
        env:
          VERSION: ${{ inputs.release-version }}

      - name: Check release version in CHANGELOG
        run: |
          if ! grep -q "## ${VERSION//./\\.}" libs/storybook/src/stories/main/changelog-additional-ui-components.mdx; then
          echo "Error: Release version ${{ inputs.release-version }} not found in changelog-additional-ui-components.mdx"
          exit 1
            fi
        env:
          VERSION: ${{ inputs.release-version }}

      # Install dependencies & build
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: '.nvmrc'

      - name: Cache npm dependencies
        uses: actions/cache@387e18722e6ff315b24a3b8b071feddd27b7bf7e # v3.4.2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Build Additional UI Components
        run: npm run build:additional-ui-components

      - name: Publish to NPM
        run: npm publish ./dist/libs/custom-ui-components --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
